name: cached_image
description: Flutter library for effortless loading and display of diverse web image formats with efficient caching, ensuring optimal performance.
version: 0.0.1
homepage: "https://github.com/rahulsharmadev-community"

publish_to: "none"

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.1+1
  equatable: ^2.0.5
  hydrated_bloc: ^9.1.2
  logs:
    git: https://github.com/rahulsharmadev-community/logs.git

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
