name: cached_image
description: Flutter library for effortless loading and display of diverse web
  image formats with efficient caching, ensuring optimal performance.
version: 1.0.2
homepage: "https://github.com/rahulsharmadev-community"

publish_to: "none"

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  dio: ^5.2.1+1
  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
